// Agregar Tweet
export const AGREGAR_TWEET = "AGREGAR_TWEET";
export const AGREGAR_TWEET_EXITO = "AGREGAR_TWEET_EXITO";
export const AGREGAR_TWEET_ERROR = "AGREGAR_TWEET_ERROR";

// Descargar Tweets
export const COMENZAR_DESCARGA_TWEETS = "COMENZAR_DESCARGA_TWEETS";
export const DESCARGA_TWEETS_EXITO = "DESCARGA_TWEETS_EXITO";
export const DESCARGA_TWEETS_ERROR = "DESCARGA_TWEETS_ERROR";

// Eliminar Tweets
export const OBTENER_TWEET_ELIMINAR = "OBTENER_TWEET_ELIMINAR";
export const TWEET_ELIMINADO_EXITO = "TWEET_ELIMINADO_EXITO";
export const TWEET_ELIMINADO_ERROR = "TWEET_ELIMINADO_ERROR";

// Alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";